# Generated by Django 2.2.2 on 2019-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190617_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='foto',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
